### ISSUE TITLE
dotnet build does not match schema for Attachment

### ISSUE THREAD

**Issue by clrudolphi** [cucumber/messages#230] opened 2024-06-26 21:33 UTC
### 👓 What did you see?

The jsonschema and the Messages.md page both describe Attachment as having a "Source" property of type 'Source'.
The dotnet build however has the "Source" property of type 'SourceReference'.

Assuming the schema is correct, the problem is on line 362 of the messages.proto file within the dotnet folder.
```
message Attachment {
  SourceReference source = 1;
  string testStepId = 2;
  string test_case_started_id = 3;
``` 

Is the schema correct? Or is the messsages.proto file correct? I note the same discrepancy in the elixer folder's version of the messages.proto file.

### ✅ What did you expect to see?

One would expect the implementation to match the schema definition.

**Comment by mpkorstanje** [comment] 2024-06-26 22:14
Due to practical problems with protobuf and the fact that in practice only json was used, we switched to generating dtos based on the json schema. These dtos are then serialised to json using what ever each language has available.

Unfortunately Cucumber is maintained mostly by volunteers (see also https://mattwynne.net/new-beginning) and as a group we currently lack the expertise, time and/or interest to keep dot net actively up to date.

However you would be welcome to help out. Given the similarities between dot net and Java I think this would be an good starting point to understand the process.

https://github.com/cucumber/messages/blob/2b20a380c2bc269f0f6573228ebd1b22ee0a913e/java/Makefile#L18-L25

In essence, a template is applied to the json schema. This generates a single file with class names. This file is then cut into multiple files which are the message class names.

We also have a weekly zoom meeting. We sometimes use this to pair program. So we could help you get started. Meeting details can be found here:

https://github.com/cucumber/community-calendar?tab=readme-ov-file

Come say hi?

**Comment by clrudolphi** [comment] 2024-06-27 01:25
Ok, if I'm understanding correctly, then the dotnet generated code is still using the old code gen approach and is not currently compliant with the Messages schema. Is that the current state? 

I've glanced at the Ruby scripts for code gen. I can add in the template for dotnet.

I've also read that there is a docker image for building? Where is the build/gen process documented? (I'm not a ruby dev and have no interest in installing the tools on my machine but more than willing to dev within a container) I'll need to know how to map the repo to a volume for the image or how to build the image with my additions and changes.

**Comment by mpkorstanje** [comment] 2024-06-27 12:57
I think you have an accurate understanding of the current situation.

When it comes to building the project, I would suggest looking at the `.github` folder for the exact details. But in principle the setup is quite uncomplicated.

1. Code and documentation is generated locally by running `make generate-all`. This generated code is then checked in. This ensures that once the code is generated, each project can be build independently of this generate job. In CI we only check if the generated code is reproducible from the current source. For example see: https://github.com/cucumber/messages/blob/main/.github/workflows/test-codegen.yml

For the `dotnet` folder, the only requirement here is that there is a Makefile with a `generate` operation.  This can then be invoked from the root of the project by adding `dotnet` to the supported language:

https://github.com/cucumber/messages/blob/2b20a380c2bc269f0f6573228ebd1b22ee0a913e/Makefile#L27

Though while developing locally, you would only have to run `make generate` from within the `dotnet` folder.

2. Each language folder has its own build  and release job. In this job you can run any language specific framework you like.  For example, to build Java, we invoke Maven. For dotnet we currently invoke make, but that is not a requirement. https://github.com/cucumber/messages/blob/574fe85d5a0ae9de12201a019fe11b5e328f2266/.github/workflows/test-java.yml

Generally speaking, within a language folder, you can follow the conventions of that language. So please feel free to add a dev container configuration to the `dotnet` folder.  

We currently don't have an image to use but the `test-codegen.yml` should provide sufficient hints as to what should be installed to run the codegen.  The contents of the base image are described here, I don't think you'll need most of these https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

**Comment by clrudolphi** [comment] 2024-06-27 16:40
> Could you point out where you've read this, then I can update/remove any references.
Eh, that was in an old, closed, issue #146. Just wanted to confirm whether that was still current info. We're good.

**Comment by clrudolphi** [comment] 2024-06-28 16:38
@mpkorstanje I am making progress and will have a PR soon. I have a question. When serializing messages to ndjson, is the order of the properties significant?
I'm creating a simple test case to validate my code that uses the .NET json serializer. I'm comparing that to a sample I've taken from the CCK (minimal feature). The step definition line in that example serializes its SourceReference with it's Location first and URI second, while my code serializes properties in the order they are defined on the class (and schema) - in this case URI first and Location after (while ignoring null property values).
My code generates:
```
{"uri":"samples/minimal/minimal.feature.ts","location":{"line":3}}
``` 
The line from the CCK example:
```
{"location":{"line":3},"uri":"samples/minimal/minimal.feature.ts"}
```

**Comment by clrudolphi** [comment] 2024-06-28 18:06
Please take a look at the PR. I welcome your feedback.

**Comment by mpkorstanje** [comment] 2024-06-28 18:27
> When serializing messages to ndjson, is the order of the properties significant?

An object is an unordered set of name/value pairs[1][2]. So we should not consider the order to be significant. 

But at the same time would be very practical if the property order is consistent between executions. 

 1. https://www.json.org/json-en.html
 2. https://www.rfc-editor.org/rfc/rfc7159#section-1
 
 > Please take a look at the PR. I welcome your feedback.
 
 Cheers! I'll take a look soon.

**Closed** 2024-07-12 16:40 UTC
